---
- name: CREATE DIRECTORY & COPY FILES
  hosts: localhost
  user: utkalreddy
  become_user: utkalreddy
  tasks:

    - name: CREATE DOCKER DIRECTORY
      file:
        path: /opt/Docker
        state: directory
        mode: "0755"
    - name: COPY DOCKERFILE
      copy:
         src: https://github.com/utkalreddy/igt_2/tree/master/webapp/dockerfile.txt
         dest: /opt/Docker
    - name: COPY WAR FILE
      copy:
         src: ../webapp/target/webapp.war
         dest: /opt/Docker
...
