---
- name: CREATE DIRECTORY & COPY FILES
  hosts: localhost
  user: utkalreddy
  tasks:

    - name: CREATE DOCKER DIRECTORY
      file:
        path: /home/utkalreddy
        state: directory
        mode: "0755"
    - name: COPY DOCKERFILE
      copy:
         src: ../Dockerfile
         dest: /home/utkalreddy
    - name: COPY WAR FILE
      copy:
         src: ../webapp/target/webapp.war
         dest: /home/utkalreddy
...
