---
- name: CREATE DIRECTORY & COPY FILES
  hosts: localhost
  user: utkalreddy
  tasks:
    - ansible.builtin.add_host:
      hostname: 54.81.179.236
      ansible_user: utkalreddy
      ansible_password: Rajini86#

    - name: CREATE DOCKER DIRECTORY
      file:
        path: /home/utkalreddy
        state: directory
        mode: "0755"
    - name: COPY DOCKERFILE
      copy:
         src: ../Dockerfile
         dest: /home/utkalreddy
    - name: COPY WAR FILE
      copy:
         src: ../webapp/target/webapp.war
         dest: /home/utkalreddy
...
