---
- name: docker
  hosts: all
  connection: local
  remote_user: utkalreddy
  become: true
  path: /opt/docker
  tasks:
    - name: TAG IMAGE WITH BUILD ID & LATEST
      shell: 
        docker build -t igp_2 .
        docker tag igp_2 utkalreddy/igp_2:latest
   
    - name: LOGIN DOCKERHUB & PUSH IMAGE ON REGISTRY
      shell:         
        docker login -u utkalreddy -p 'Rajini86#'
        docker push utkalreddy/igp_2:latest
 
...
