---
- name: IMAGE PUSH
  hosts: localhost
  user: utkalreddy
  tasks:
    - name: TAG IMAGE WITH BUILD ID & LATEST
      shell:
        cd "/opt/docker"
        docker build -t {{ JOB_NAME }}:v1.{{ BUILD_ID }} .
        docker tag {{ JOB_NAME }}:v1.{{ BUILD_ID }} utkalreddy/{{ JOB_NAME }}:v1.{{ BUILD_ID }}
        docker tag {{ JOB_NAME }}:v1.{{ BUILD_ID }} utkalreddy/{{ JOB_NAME }}:latest

    - name: LOGIN DOCKERHUB & PUSH IMAGE ON REGISTRY
      shell: |        
        docker login -u {{ dockerhub_user }} -p {{ dockerhub_pass }} https://hub.docker.com/repository/docker
        docker push utkalreddy/{{ JOB_NAME }}:v1.{{ BUILD_ID }}
        docker push utkalreddy/{{ JOB_NAME }}:latest

    - name: REMOVE OLD IMAGES FROM SERVER
      shell: docker rmi -f $(docker images 'utkalreddy:/{{ JOB_NAME }}' -a -q) &> /dev/null

    - name: LOGOUT DOCKERHUB
      shell: docker logout
